services:
  - type: web
    name: chess-multiplayer
    env: node
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
    buildFilter:
      paths:
      - src/**/*.ts
      - prisma/**/*
      - package.json
      - package-lock.json
      - tsconfig.json